In [5]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
da = pd.read_csv("/content/fraud.csv" )
da.drop(['nameOrig', 'nameDest'], inplace=True, axis=1)
da.head(10)

step      type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   PAYMENT   9839.64      170136.00       160296.36             0.0   
1     1   PAYMENT   1864.28       21249.00        19384.72             0.0   
2     1  TRANSFER    181.00         181.00            0.00             0.0   
3     1  CASH_OUT    181.00         181.00            0.00         21182.0   
4     1   PAYMENT  11668.14       41554.00        29885.86             0.0   
5     1   PAYMENT   7817.71       53860.00        46042.29             0.0   
6     1   PAYMENT   7107.77      183195.00       176087.23             0.0   
7     1   PAYMENT   7861.64      176087.23       168225.59             0.0   
8     1   PAYMENT   4024.36        2671.00            0.00             0.0   
9     1     DEBIT   5337.77       41720.00        36382.23         41898.0   

   newbalanceDest  isFraud  
0            0.00        0  
1            0.00        0  
2            0.00        1  
3            0.00        1  
4            0.00        0  
5            0.00        0  
6            0.00        0  
7            0.00        0  
8            0.00        0  
9        40348.79        0

In [6]:
# to convert the string column to corresponding numbers for every unique value
from sklearn import preprocessing  
label_encoder = preprocessing.LabelEncoder()
da['type']= label_encoder.fit_transform(da['type'])
# converting the labels into a numeric form so as to convert them into the machine-readable form
da.head(10)


step  type    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1     3   9839.64      170136.00       160296.36             0.0   
1     1     3   1864.28       21249.00        19384.72             0.0   
2     1     4    181.00         181.00            0.00             0.0   
3     1     1    181.00         181.00            0.00         21182.0   
4     1     3  11668.14       41554.00        29885.86             0.0   
5     1     3   7817.71       53860.00        46042.29             0.0   
6     1     3   7107.77      183195.00       176087.23             0.0   
7     1     3   7861.64      176087.23       168225.59             0.0   
8     1     3   4024.36        2671.00            0.00             0.0   
9     1     2   5337.77       41720.00        36382.23         41898.0   

   newbalanceDest  isFraud  
0            0.00        0  
1            0.00        0  
2            0.00        1  
3            0.00        1  
4            0.00        0  
5            0.00        0  
6            0.00        0  
7            0.00        0  
8            0.00        0  
9        40348.79        0

In [7]:
X = da.iloc[:, :-1].values # storing in X all columns except the last one 
y = da.iloc[:, -1].values # storing in y the last column 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

da['type'].unique()


array([3, 4, 1, 2, 0])

In [8]:
# training the naive bayes model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [9]:
# making predictions on the testing set to predict features
y_pred = gnb.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Gaussian Naive Bayes model accuracy(in %): 98.26305171480588


In [29]:
# training the K nearest neigbhour model on training set
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [35]:
y_predict =knn.predict(X_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [36]:
# Calculate the accuracy of the model
print(knn.score(X_test, y_test)*100)

99.89174826551198


In [28]:
from numpy import mean
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn, X_train, y_train, cv=10, scoring = 'accuracy')
 # cross validation on k nearest neighbor
print('Cross Validation accuracy scores: %s' % scores)

Cross Validation accuracy scores: [0.99913889 0.99876984 0.99901587 0.99876984 0.99901587 0.99913889
 0.99876984 0.99876984 0.99876984 0.99864682]


In [31]:
scores = cross_val_score(gnb, X_train, y_train, cv=10, scoring = 'accuracy' )
 # cross validation on naive bayes model
print('Cross Validation accuracy scores: %s' % scores)

Cross Validation accuracy scores: [0.98203961 0.98449994 0.98068643 0.98326977 0.98191659 0.98425391
 0.97773404 0.98265469 0.98351581 0.98523804]


In [32]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))

Confusion Matrix

[[19968   332]
 [   21     2]]

Accuracy: 0.98

Micro Precision: 0.98
Micro Recall: 0.98


In [37]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_predict)
print('Confusion Matrix\n')
print(confusion)

from sklearn.metrics import accuracy_score, precision_score, recall_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_predict)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_predict, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_predict, average='micro')))

Confusion Matrix

[[20297     3]
 [   19     4]]

Accuracy: 1.00

Micro Precision: 1.00
Micro Recall: 1.00


The model with better accuracy is the better one which is the model
using K nearest neighbour (k = 5)